### ISSUE TITLE
Missing local-docker-compose directory

### ISSUE THREAD

**Issue by bigsing** [HCL-TECH-SOFTWARE/dx-docker-compose#4]
The readme assumes the local-docker-compose directory has already been created, "Start by cloning this repository locally and cd into the local-docker-compose directory". It's unclear whether this was to be included in the project or something the user should create. I believe updating accordingly would reduce confusion for new users.

**Comment by chandrumani** [comment]
It is supposed to be `dx-docker-compose`. Will be raising the PR to update the documentation.

**Comment by timpeteler** [comment]
Fixed with https://github.com/HCL-TECH-SOFTWARE/dx-docker-compose/pull/3
