### ISSUE TITLE
Support design studio from cf196

### ISSUE THREAD

**Issue by DanieleVistalli** [HCL-TECH-SOFTWARE/dx-docker-compose#5]
Cf196 introduces design studio.

It would be useful to have support for it too in order to easily test.

A mechanism to support containerized releases version will also be useful in order to support multiple versions.

For instance over cf196 is important to support design studio and so on.

**Comment by timpeteler** [comment]
Design studio support was added with https://github.com/HCL-TECH-SOFTWARE/dx-docker-compose/pull/6
