### ISSUE TITLE
Windows Docker desktop cannot load images

### ISSUE THREAD

**Issue by sting0391** [HCL-TECH-SOFTWARE/dx-docker-compose#8]
E:\VMware\PortalRuntimeFile\PortalRuntime>load.bat E:\VMware\PortalRuntimeFile\hcl-dx-kubernetes-v95-CF197
Loaded image: hcl/dx/content-composer:v1.10.0_20210806-1258
Loaded image: hcl/dx/image-processor:v1.10.0_20210806-1300
Loaded image: hcl/dx/postgres:v1.10.0_20210806-1302
Error processing tar file(exit status 1): archive/tar: invalid tar header
Loaded image: hcl/dx/ringapi:v1.10.0_20210806-1311
Error processing tar file(gzip: invalid checksum):
"Updating properties file with image tags"
此时不应有 (。

E:\VMware\PortalRuntimeFile\PortalRuntime>
====================
I failed in loading images to my docker desktop . error log is above.

**Comment by timpeteler** [comment]
We were not able to reproduce the issue with the latest updates.
Please retry and open up the issue in case you still see the issue.
